### ISSUE TITLE
Potential vulnerability due to quinn-proto dependency crate

### ISSUE THREAD

**Issue by snehilzs** [ZettaScaleLabs/zenoh#3]
### Describe the bug

Code audit shows potential vulnerability from the quinn-proto dependency crate. Receiving QUIC frames containing a frame with unknown frame type could lead to a panic. 

Details are:
Crate:     quinn-proto
Version:   0.10.4
Title:     Denial of service in Quinn servers
Date:      2023-09-21
ID:        RUSTSEC-2023-0063
URL:       https://rustsec.org/advisories/RUSTSEC-2023-0063
Severity:  7.5 (high)

Solution:  Upgrade to ^0.9.5 OR >=0.10.5

### To reproduce

NA

### System info

NA

**Comment by wyfo** [comment]
@oteffahi Is this issue still relevant?

**Comment by oteffahi** [comment]
@wyfo We're still using that version of the crate; so the issue is still relevant.

**Comment by wyfo** [comment]
Should we move it to the origin repository?

**Comment by oteffahi** [comment]
We shouldn't put security vulnerabilities in the spotlight before we resolve them 😅

**Comment by oteffahi** [comment]
@gabrik can we bump Quinn?

**Comment by gabrik** [comment]
> @gabrik can we bump Quinn?

sure, but I think it will have a impact on the QUIC transport, as there have been API changes in quinn, so it is not just a bump of the crate

**Comment by wyfo** [comment]
> We shouldn't put security vulnerabilities in the spotlight before we resolve them 😅

Mouais...

**Comment by oteffahi** [comment]
Fixed by updating crate version in https://github.com/eclipse-zenoh/zenoh/pull/1086
